export const GET_BILL_BEGIN = 'GET_BILL_BEGIN';
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS';
export const GET_BILL_ERROR = 'GET_BILL_ERROR';

export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';
